### ISSUE TITLE
Would be nice to support raspberry pi / ARM

### ISSUE THREAD

**Issue by brianegge** [owntone/owntone-container#2]
Linux 5.15.0-1050-raspi #53-Ubuntu SMP PREEMPT Thu Mar 21 10:02:47 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

**Comment by hacketiwack** [comment]
There is now a version for arm64 as well.
As I don't own a Raspberry PI myself, I can't test this image.

**Comment by brianegge** [comment]
When I do a docker pull it says it only supports x86, which is what the documentation says at well. I’m happy to test, but there must be a different container name.

**Comment by hacketiwack** [comment]
@brianegge you have to pull with the option `--platform linux/arm64`.
Like this:

```shell
docker pull --platform linux/arm64 docker.io/owntone/owntone:latest
```

Or if you use `podman`

```shell
podman pull --platform linux/arm64 docker.io/owntone/owntone:latest
```

The option --platform works as well with the `run` command, like: `docker run --platform linux/arm64 ...` or `docker run --platform linux/arm64 ...`
