### ISSUE TITLE
arm64 container doesn't fully start

### ISSUE THREAD

**Issue by brianegge** [owntone/owntone-container#3]
It seems to hang during the startup.

 CONTAINER ID   IMAGE                    COMMAND                  CREATED         STATUS                     PORTS                                       NAMES
9fa543105adc   owntone/owntone:latest   "/sbin/init"             4 minutes ago   Up 4 minutes (unhealthy)                                               OwnTone 

* /proc is already mounted
mount: permission denied (are you root?)
 * Unable to mount tmpfs on /run.
 * Can't continue.
 * Mounting /run ...   OpenRC 0.52.1 is starting up Linux 5.15.0-1050-raspi (aarch64) [DOCKER]
 * Caching service dependencies ... [ ok ]
mkdir: can't create directory '/sys/fs/cgroup/openrc.syslog': Read-only file system
 * Starting busybox syslog ... [ ok ]
mkdir: can't create directory '/sys/fs/cgroup/openrc.dbus': Read-only file system
 * /run/dbus: creating directory
 * /run/dbus: correcting owner
 * Starting System Message Bus ... [ ok ]
mkdir: can't create directory '/sys/fs/cgroup/openrc.avahi-daemon': Read-only file system
 * Starting avahi-daemon ... [ ok ]
mkdir: can't create directory '/sys/fs/cgroup/openrc.avahi-dnsconfd': Read-only file system
 * Starting avahi-dnsconfd ... [ ok ]
mkdir: can't create directory '/sys/fs/cgroup/openrc.owntone': Read-only file system
[2024-04-16 10:31:13] [  LOG]     main: OwnTone version 28.9 taking off
[2024-04-16 10:31:13] [  LOG]     main: Built with:
[2024-04-16 10:31:13] [  LOG]     main: - ffmpeg
[2024-04-16 10:31:13] [  LOG]     main: - Spotify
[2024-04-16 10:31:13] [  LOG]     main: - librespot-c
[2024-04-16 10:31:13] [  LOG]     main: - LastFM
[2024-04-16 10:31:13] [  LOG]     main: - Chromecast
[2024-04-16 10:31:13] [  LOG]     main: - MPD
[2024-04-16 10:31:13] [  LOG]     main: - Websockets
[2024-04-16 10:31:13] [  LOG]     main: - ALSA
[2024-04-16 10:31:13] [  LOG]     main: - Webinterface
[2024-04-16 10:31:13] [  LOG]     main: - Regex
 * Starting owntone ... [ ok ]

**Comment by hacketiwack** [comment]
> mount: permission denied (are you root?)

How are you starting the container? With which user?

Moreover, what is your operating system?

If you have an OS using `systemd`, you can automate the startup of containers with it (documentation with [`Podman`](https://github.com/owntone/owntone-container?tab=readme-ov-file#systemd) and with [`Docker`](https://docs.docker.com/config/daemon/systemd/)).

**Comment by hacketiwack** [comment]
What is the status of this ticket?
Do you have it working yet?

**Comment by brianegge** [comment]
OS `Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-1050-raspi aarch64)`

`sudo docker run -d --name=OwnTone --network=host -e UID=$(id -u) -e GID=$(id -g) -v $HOME/OwnTone/etc:/etc/owntone -v /mnt/elements/Music/iTunes:/srv/media -v $HOME/OwnTone/cache:/var/cache/owntone --restart unless-stopped docker.io/owntone/owntone:latest`

Note, this time it found the aarch64 without needing to specify the platform

I have several other containers on the host working fine.

**Comment by hacketiwack** [comment]
Thanks for the additional information.
So I understand that you have the following directories created:
- `$HOME/OwnTone/etc`, containing as well your configuration file owntone.conf
- `$HOME/OwnTone/cache`, containing the OwnTone database
- `/mnt/elements/Music/iTunes`, containing your media

Regarding the following errors:

> mkdir: can't create directory '/sys/fs/cgroup/openrc.syslog': Read-only file system
> mkdir: can't create directory '/sys/fs/cgroup/openrc.dbus': Read-only file system
> mkdir: can't create directory '/sys/fs/cgroup/openrc.avahi-daemon': Read-only file system
> mkdir: can't create directory '/sys/fs/cgroup/openrc.avahi-dnsconfd': Read-only file system

Maybe you have to add the following volume to your run command:

`-v /sys/fs/cgroup:/sys/fs/cgroup`

**Comment by brianegge** [comment]
I added the cgroup and am closer. Now it complains it can't write to the database.

```
[2024-04-26 11:41:45] [  LOG]     mdns: Avahi state change: Client registering
[2024-04-26 11:41:45] [  LOG]       db: Configured to use database file '/var/cache/owntone/database.db'
[2024-04-26 11:41:45] [  LOG]       db: Could not open '/var/cache/owntone/database.db': unable to open database file
[2024-04-26 11:41:45] [FATAL]       db: Could not open database
[2024-04-26 11:41:45] [FATAL]     main: Database init failed
[2024-04-26 11:41:45] [  LOG]     main: mDNS deinit
[2024-04-26 11:41:45] [  LOG]     main: Exiting.
 * Starting owntone ... [ ok ]
```
If I go into the container, I see the folder and can write to it:
```
$ sudo docker exec -it 1ee767d85003 sh
/ # ls /var/cache
apk         fontconfig  misc        owntone
/ # ls /var/cache/owntone/
/ # touch /var/cache/owntone/foo
/ # ls /var/cache/owntone/
foo
/ #
```
exiting the container show the file I created in the host folder:
```
~
$ ls OwnTone/cache/
foo
```

**Comment by hacketiwack** [comment]
That's weird, indeed.

What are the permissions on your directory `$HOME/OwnTone/cache`?
What are the user and permissions on the created file foo? 

Generally speaking, I would recommend you:
- to create a user/group for your container (a separate user for each of your containers actually).
- provide the permissions to the user created above to the mounted directories (755)
- configure your containers to start with systemd (see this section about [systemd here](https://github.com/owntone/owntone-container?tab=readme-ov-file#systemd).

To use the systemd-way to start your container, you'll need podman. You can then remove the docker command.
The podman command is a replacement for the docker command.

Notes: Also, looking at your system, it seems you have a rather old version of the Gnu/Linux kernel: (GNU/Linux 5.15.0-1050-raspi aarch64). It might be worth upgrading.

On my side, I installed a virtual machine with Ubuntu 22.04 starting successfully the container with podman.
I didn't manage yet to emulate a Raspberry PI to reproduce your setup as close as possible to reality.

**Comment by brianegge** [comment]
Thanks you for the help. I needed to chown my cache directory to be the same as my user - it was owned by root. 

I'm hoping to stay on `22.04.4 LTS` for a while. I'm using portainer to manage my docker containers. I'll take a look at podman, which is what we're using at the office.
